# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-17 21:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopper_challenge', '0002_remove_applicant_zipcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicant',
            name='workflow_state',
            field=models.CharField(default='applied', max_length=100),
        ),
    ]
