# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-18 01:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopper_challenge', '0003_auto_20170417_2138'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applicant',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='applicant',
            name='updated_at',
        ),
    ]
